###############################################################
#  Generated by:      Cadence Innovus 22.33-s094_1
#  OS:                Linux x86_64(Host ID kasirga)
#  Generated on:      Mon Jul 29 05:20:08 2024
#  Design:            c0_soc
#  Command:           write_io_file -locations c0_soc.save.io
###############################################################

(globals
    version = 3
    io_order = default
)
(iopad
    (topright
	(inst name="trcorner"	cell="PCORNER" )
    )
    (top
	(inst  name="u_pads_pwr/VSS_0"	offset=200 place_status=placed )
	(inst  name="PDDW0204CDG_IN0"	offset=400 place_status=placed )
	(inst  name="PDDW0204CDG_IN1"	offset=600 place_status=placed )
	(inst  name="u_pads_pwr/VDDPST_0"	offset=800 place_status=placed )
    )
    (topleft
	(inst name="tlcorner"	cell="PCORNER" )
    )
    (left
	(inst  name="u_pads_pwr/VDDPST_1"	offset=200 place_status=placed )
	(inst  name="PDDW0204CDG_IN_RSTN"	offset=400 place_status=placed )
	(inst  name="PDDW0204CDG_IN_CLK"	offset=600 place_status=placed )
	(inst  name="u_pads_pwr/VDD_0"	offset=800 place_status=placed )
    )
    (bottomleft
	(inst name="blcorner"	cell="PCORNER" )
    )
    (bottom
	(inst  name="u_pads_pwr/VDD2POC"	offset=200 place_status=placed )
	(inst  name="PDDW0204CDG_OUT0"	offset=400 place_status=placed )
	(inst  name="PDDW0204CDG_OUT1"	offset=600 place_status=placed )
	(inst  name="u_pads_pwr/VDD_1"	offset=800 place_status=placed )
    )
    (bottomright
	(inst name="brcorner"	cell="PCORNER" )
    )
    (right
	(inst  name="u_pads_pwr/VSS_1"	offset=200 place_status=placed )
	(inst  name="PDDW0204CDG_OUT2"	offset=400 place_status=placed )
	(inst  name="PDDW0204CDG_OUT3"	offset=600 place_status=placed )
	(inst  name="PDDW0204CDG_OUT4"	offset=800 place_status=placed )
    )
)
